apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argo-events-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
  - resources/eventbus-jetstream.yaml
  - resources/sync-success-eventsource.yaml
  - resources/webhook-service.yaml
  - resources/workflow-trigger-sensor-app.yaml
  - resources/webhook-ingress.yaml
  - resources/role-binding.yaml