apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
  - resources/eventbus-jetstream.yaml
  - resources/sync-success-eventsource.yaml
  - resources/webhook-service.yaml
  - resources/workflow-trigger-sensor-app.yaml
  - resources/webhook-ingress.yaml

patches:
  - path: patches/replace-namespace.yaml
    target:
      kind: Deployment
      name: controller-manager
  - path: patches/replace-namespace.yaml
    target:
      kind: ConfigMap
      name: argo-events-controller-config
  - path: patches/replace-namespace.yaml
    target:
      kind: ServiceAccount
      name: argo-events-sa
  - path: patches/replace-namespace.yaml
    target:
      kind: Role
      name: argo-events-role
  - path: patches/replace-namespace-RB.yaml
    target:
      kind: RoleBinding
      name: argo-events-role-binding