image:
  version: '3.0'
phase: prod
rollout:
  enabled: true
  strategy:
    canary:
      analysis:
        args:
        - name: container-name
          value: app-prod-my-app
        - name: stable-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: latest-hash
          valueFrom:
            podTemplateHashValue: Latest
        templates:
        - clusterScope: true
          templateName: http-server-success-rate-comparison
      canaryService: app-prod-my-app-canary-svc
      scaleDownDelaySeconds: 3
      stableService: app-prod-my-app-svc
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      trafficRouting:
        nginx:
          stableIngress: app-prod-my-app-ingress
