image:
  version: '1.0'
phase: prod
rollout:
  enabled: true
  strategy:
    canary:
      canaryService: app-prod-my-app-canary-svc
      stableService: app-prod-my-app-svc
      trafficRouting:
        nginx:
          stableIngress: app-prod-my-app-ingress
      steps:
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 40
      - pause:
          duration: 40s
      - setWeight: 60
      - pause:
          duration: 20s
      - setWeight: 80
      - pause:
          duration: 20s
