apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-pods
spec:
  endpoints:
    - port: metrics
      path: /q/metrics
      scheme: http
      interval: 10s
  namespaceSelector:
    matchNames:
      - app-test
      - app-prod
  selector:
    matchLabels:
      prometheus.io/scrape-app: "true"