apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-pods
spec:
  podMetricsEndpoints:
    - port: "(.*-)?metrics(-.*)?"
      relabelings:
      - action: labelmap
        regex: __meta_kubernetes_(namespace|pod_name|pod_controller_name)
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(app_)kubernetes_io_(part_of|name|component|instance)
        replacement: $1$2
      - action: labelmap
        regex: __meta_kubernetes_pod_annotation_(app_)kubernetes_io_(version)
        replacement: $1$2
      # Stand-in replacement for Argos label
      - action: replace
        replacement: app
        sourceLabels:
        - __address__
        targetLabel: prometheus
  # Generic selector
  selector:
    matchLabels:
      prometheus.io/scrape-app: "true"