apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argo-namespace.yaml
  - resources/argo-workflow-ingress.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.4/install.yaml
  - resources/eventbus-jetstream.yaml
  #- resources/sync-success-eventsource.yaml
  #- resources/webhook-service.yaml
  #- resources/workflow-templates.yaml
  #- resources/workflow-trigger-sensor-app.yaml

patches:
 - path: patches/change-argo-server-args.yaml
   target:
     kind: Deployment
     name: argo-server
 - path: patches/change-readiness-probe-to-http.yaml
   target:
     kind: Deployment
     name: argo-server