apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - resources/argocd-ingress.yaml

patches:
  - path: patches/update-server-args.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: patches/notification-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-notifications-cm
  - path: patches/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm