---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  webhook:
    appSyncSuccess:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /appSyncSuccess
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST