name: Deploy-Docs 
on:
  workflow_dispatch: # Allow manual trigger
  push:
    tags-ignore:
      - '**' # Ignore any tags here
    branches:
      - main    
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  buildAndDeploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    # This environment is required!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: '3.x' # Uses latest 3.x version.
      - name: Install dependencies
        # Alternatively: pip install mkdocs
        run: pip install -r requirements.txt
      - name: Build Docs
        run: mkdocs build
      - name: Configure GitHub Pages
        # I have no idea if this actually needed...
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site/' # MkDocs builds to site/ by default
      - name: Deploy to GitHub Pages
        id: deployment # This is required for environment
        uses: actions/deploy-pages@v2